/** @format */

import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<nav
					style={{
						display: 'flex',
						justifyContent: 'space-around',
						padding: '16px',
						// backgroundColor: "#f0f0f0",
					}}>
					<Link href='./articles'>Articles</Link>
					<Link href='/'>Home</Link>
					<Link href='./posts'>Posts</Link>
				</nav>
				{children}
			</body>
		</html>
	);
}
